'use client';

import Navbar from '@/components/Navbar';
import Link from 'next/link';

export default function About() {
  return (
    <main className="min-h-screen bg-base-100 text-base-content">
      <Navbar />

      {/* Animated Background Blobs */}
      <div className="fixed inset-0 -z-10 pointer-events-none overflow-hidden">
        <div className="absolute top-[15%] left-[5%] w-96 h-96 bg-primary opacity-20 rounded-full filter blur-3xl animate-pulse" style={{ animationDuration: '10s' }}></div>
        <div className="absolute bottom-[10%] right-[5%] w-80 h-80 bg-secondary opacity-20 rounded-full filter blur-3xl animate-pulse" style={{ animationDuration: '15s' }}></div>
      </div>

      <div className="container mx-auto px-4 py-24">
        <div className="max-w-4xl mx-auto">
          <div className="badge badge-primary badge-outline mb-6 px-4 py-2 text-lg">
            About Us
          </div>

          <h1 className="text-4xl md:text-5xl font-extrabold mb-6 text-primary">
            Empowering Students with AI
          </h1>

          <p className="text-lg text-base-content/70 mb-8">
            BreakMyAssignment helps students understand and complete their assignments more effectively using AI.
          </p>

          <div className="bg-base-200 rounded-xl p-6 shadow-md border border-base-300 mb-10">
            <h2 className="text-2xl font-bold text-primary mb-4">Our Mission</h2>
            <p>
              We believe every student deserves clear assignment guidance. Our AI breaks down tasks into manageable steps, saving time and improving academic outcomes.
            </p>
          </div>

          <div className="mb-10">
            <h2 className="text-2xl font-bold text-primary mb-4">How We Started</h2>
            <p>
              Created by students and educators who struggled with vague assignments, BreakMyAssignment uses AI to bring structure, clarity, and support to your academic life.
            </p>
          </div>

          <div className="mb-10">
            <h2 className="text-2xl font-bold text-primary mb-4">Our Technology</h2>
            <p>
              Using GPT-4 and NLP, our system reads assignment prompts, understands academic language, and suggests steps, references, and estimated time to complete.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 my-12">
            <div className="card bg-base-200 shadow-sm hover:shadow-md transition-all">
              <div className="card-body items-start">
                <span className="text-3xl">🔍</span>
                <h3 className="text-xl font-semibold text-base-content">Detailed Analysis</h3>
                <p className="text-base-content/70">We turn confusing prompts into structured tasks with time estimates.</p>
              </div>
            </div>

            <div className="card bg-base-200 shadow-sm hover:shadow-md transition-all">
              <div className="card-body items-start">
                <span className="text-3xl">⏱️</span>
                <h3 className="text-xl font-semibold text-base-content">Time-Saving</h3>
                <p className="text-base-content/70">Jump straight into action with clear next steps generated by AI.</p>
              </div>
            </div>

            <div className="card bg-base-200 shadow-sm hover:shadow-md transition-all">
              <div className="card-body items-start">
                <span className="text-3xl">🎓</span>
                <h3 className="text-xl font-semibold text-base-content">Academic Success</h3>
                <p className="text-base-content/70">Students improve their grades by understanding what’s required and how to do it.</p>
              </div>
            </div>
          </div>

          <div className="flex justify-center mt-12">
            <Link 
              href="/upload" 
              className="btn btn-primary px-8 text-lg font-bold shadow-md hover:shadow-lg transition-all duration-300"
            >
              Try It Now
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
